# The content type we're changing settings for is landing_page.
'%target_content_type%': 'landing_page'
actions:
  content_types:
    plugin: 'change'
    path: ['content_types', '%target_content_type%']
    actions:
      add_type:
        value: 'user'
  content_type_modes:
    plugin: 'add'
    path: ['content_type_modes', '%target_content_type%']
    actions:
      add_type_mode:
        value: 
          - 'full'